# Generated by Django 5.1.5 on 2025-02-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='locker_id',
            new_name='lockeritem',
        ),
    ]
