# Generated by Django 5.1.5 on 2025-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_rename_is_paid_payment_status_alter_lockeritem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/payment_images/'),
        ),
    ]
