# Generated by Django 5.1.5 on 2025-02-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_rename_locker_id_item_lockeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lockeritem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.lockeritem'),
        ),
    ]
