# Generated by Django 5.1.5 on 2025-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_payment_payment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id_room',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
