# Generated by Django 5.1.5 on 2025-02-04 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_survey_created_by_survey_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_img'),
        ),
    ]
