# Generated by Django 5.1.5 on 2025-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_room_id_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
