# Generated by Django 5.1.5 on 2025-02-04 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockeritem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='lockeritem',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='lockeritem',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='lockeritem',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='lockeritem',
            name='status',
        ),
        migrations.AlterField(
            model_name='lockeritem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Chờ nhận', max_length=50)),
                ('locker_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='apartment.lockeritem')),
            ],
        ),
    ]
