# Generated by Django 5.1.5 on 2025-02-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_remove_lockeritem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='locker_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apartment.lockeritem'),
        ),
    ]
